name: Auto-Assign Issue to Creator

on:
  issues:
    types: [opened]

jobs:
  assign-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue creator
        uses: actions-ecosystem/action-assign@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.issue.user.login }}
