name: Destroy Container App

on:
  pull_request:
    types: [closed]

jobs:
  destroy-container-app:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Destroy Container App
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az containerapp delete --name my-container-app --resource-group my-resource-group --yes
